(function() {var implementors = {};
implementors['core_foundation'] = [];implementors['core_graphics'] = ["impl <a class='trait' href='core_foundation/base/trait.TCFType.html' title='core_foundation::base::TCFType'>TCFType</a>&lt;<a class='type' href='core_graphics/data_provider/type.CGDataProviderRef.html' title='core_graphics::data_provider::CGDataProviderRef'>CGDataProviderRef</a>&gt; for <a class='struct' href='core_graphics/data_provider/struct.CGDataProvider.html' title='core_graphics::data_provider::CGDataProvider'>CGDataProvider</a>","impl <a class='trait' href='core_foundation/base/trait.TCFType.html' title='core_foundation::base::TCFType'>TCFType</a>&lt;<a class='type' href='core_graphics/font/type.CGFontRef.html' title='core_graphics::font::CGFontRef'>CGFontRef</a>&gt; for <a class='struct' href='core_graphics/font/struct.CGFont.html' title='core_graphics::font::CGFont'>CGFont</a>",];implementors['cocoa'] = ["impl <a class='trait' href='core_foundation/base/trait.TCFType.html' title='core_foundation::base::TCFType'>TCFType</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.pointer.html'>*const <a class='struct' href='core_graphics/data_provider/struct.__CGDataProvider.html' title='core_graphics::data_provider::__CGDataProvider'>__CGDataProvider</a></a>&gt; for <a class='struct' href='core_graphics/data_provider/struct.CGDataProvider.html' title='core_graphics::data_provider::CGDataProvider'>CGDataProvider</a>","impl <a class='trait' href='core_foundation/base/trait.TCFType.html' title='core_foundation::base::TCFType'>TCFType</a>&lt;<a href='http://doc.rust-lang.org/nightly/std/primitive.pointer.html'>*const <a class='struct' href='core_graphics/font/struct.__CGFont.html' title='core_graphics::font::__CGFont'>__CGFont</a></a>&gt; for <a class='struct' href='core_graphics/font/struct.CGFont.html' title='core_graphics::font::CGFont'>CGFont</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
